[package]
name = "beaver-pass"
version = "0.0.1"
authors = ["Alex Zepeda <alex.zepeda@autodesk.com>"]

[dependencies]
byteorder = "1"
syslog = "~3.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
glob = "0.2"
regex = "*"
subprocess = "0.1"
